#include "StaticMesh.h"
#include "SceneExporter.h"
#include <algorithm>
#include "MeshBounds.h"

namespace pure {
namespace {
    static bool SameGeometryByAccessorId(const GLTFGeometry &a,const GLTFGeometry &b){ if(a.mode!=b.mode) return false; if(static_cast<bool>(a.indicesAccessorIndex)!=static_cast<bool>(b.indicesAccessorIndex)) return false; if(a.indicesAccessorIndex && b.indicesAccessorIndex && (*a.indicesAccessorIndex!=*b.indicesAccessorIndex)) return false; if(a.attributes.size()!=b.attributes.size()) return false; auto makeList=[](const GLTFGeometry &g){ std::vector<std::pair<std::string,std::size_t>> v; v.reserve(g.attributes.size()); for(const auto &at: g.attributes){ if(!at.accessorIndex) return std::vector<std::pair<std::string,std::size_t>>{}; v.emplace_back(at.name,*at.accessorIndex);} std::sort(v.begin(),v.end(),[](auto &l,auto &r){ if(l.first!=r.first) return l.first<r.first; return l.second<r.second;}); return v; }; auto la=makeList(a); auto lb=makeList(b); if(la.empty()||lb.empty()) return false; return la==lb; }

    static void CopyMaterials(Model &dst,const GLTFModel &src){ dst.materials.reserve(src.materials.size()); for(const auto &m: src.materials){ Material pm; pm.name=m.name; dst.materials.push_back(std::move(pm)); } }
    static void CopyScenes(Model &dst,const GLTFModel &src){ dst.scenes.reserve(src.scenes.size()); for(const auto &s: src.scenes){ Scene ps; ps.name=s.name; ps.nodes.reserve(s.nodes.size()); for(auto ni: s.nodes) ps.nodes.push_back((int32_t)ni); BoundingBox bb; bb.aabb=s.worldAABB; bb.obb.reset(); bb.sphere.reset(); ps.boundsIndex=dst.internBounds(bb); dst.scenes.push_back(std::move(ps)); } }
    static void CopyMeshNodesAndTransforms(Model &dst,const GLTFModel &src){ dst.mesh_nodes.reserve(src.nodes.size()); for(const auto &n: src.nodes){ MeshNode pn; pn.name=n.name; pn.children.reserve(n.children.size()); for(auto c: n.children) pn.children.push_back((int32_t)c); glm::mat4 local=glm::mat4(n.localMatrix()); glm::mat4 world=glm::mat4(n.worldMatrix); int32_t lidx=dst.internMatrix(local); pn.localMatrixIndexPlusOne = lidx>=0? lidx+1:0; int32_t widx=dst.internMatrix(world); pn.worldMatrixIndexPlusOne = widx>=0? widx+1:0; if(!n.hasMatrix){ MeshNodeTransform tf; tf.translation=glm::vec3(n.translation); tf.rotation=glm::quat(n.rotation); tf.scale=glm::vec3(n.scale); if(!(tf.translation==MeshNodeTransform{}.translation && tf.rotation==MeshNodeTransform{}.rotation && tf.scale==MeshNodeTransform{}.scale)){ int32_t tidx=dst.internTRS(tf); pn.trsIndexPlusOne=tidx+1; } } pn.boundsIndex=kInvalidBoundsIndex; dst.mesh_nodes.push_back(std::move(pn)); } }
    struct UniqueGeometryMapping { std::vector<int32_t> uniqueRepGeomPrimIdx; std::vector<int32_t> geomIndexOfPrim; };
    static UniqueGeometryMapping BuildUniqueGeometryMapping(const GLTFModel &src){ UniqueGeometryMapping map; const auto &prims=src.primitives; map.geomIndexOfPrim.assign(prims.size(), -1); for(int32_t i=0;i<(int32_t)prims.size();++i){ const auto &g=prims[(size_t)i].geometry; int32_t found=-1; for(int32_t u=0;u<(int32_t)map.uniqueRepGeomPrimIdx.size();++u){ if(SameGeometryByAccessorId(g, prims[(size_t)map.uniqueRepGeomPrimIdx[(size_t)u]].geometry)){ found=u; break; } } if(found==-1){ map.uniqueRepGeomPrimIdx.push_back(i); map.geomIndexOfPrim[(size_t)i]=(int32_t)map.uniqueRepGeomPrimIdx.size()-1; } else map.geomIndexOfPrim[(size_t)i]=found; } return map; }
    static void CreateUniqueGeometryEntries(Model &dst,const GLTFModel &src,const UniqueGeometryMapping &map){ const auto &prims=src.primitives; dst.geometry.reserve(map.uniqueRepGeomPrimIdx.size()); for(int32_t u=0;u<(int32_t)map.uniqueRepGeomPrimIdx.size();++u){ int32_t i=map.uniqueRepGeomPrimIdx[(size_t)u]; const auto &g=prims[(size_t)i].geometry; Geometry pg; pg.mode=g.mode; pg.attributes.reserve(g.attributes.size()); for(size_t ai=0; ai<g.attributes.size(); ++ai){ const auto &a=g.attributes[ai]; GeometryAttribute ga; ga.id=(uint8_t)ai; ga.name=a.name; ga.count=a.count; ga.componentType=a.componentType; ga.type=a.type; ga.format=a.format; ga.data=a.data; pg.attributes.push_back(std::move(ga)); } ComputeGeometryBoundsFromGLTF(dst, g, pg); if(g.indices) pg.indicesData=*g.indices; if(g.indexCount && g.indexComponentType){ pg.indices=GeometryIndicesMeta{ *g.indexCount, *g.indexComponentType }; pg.indices->indexType=g.indexType; } dst.geometry.push_back(std::move(pg)); } }
    static void BuildSubMeshes(Model &dst,const GLTFModel &src,const UniqueGeometryMapping &map){ const auto &prims=src.primitives; dst.subMeshes.reserve(prims.size()); for(int32_t i=0;i<(int32_t)prims.size();++i){ const auto &p=prims[(size_t)i]; SubMesh sm; sm.geometry=map.geomIndexOfPrim[(size_t)i]; sm.material = p.material ? std::optional<int32_t>((int32_t)*p.material) : std::optional<int32_t>{}; dst.subMeshes.push_back(std::move(sm)); } }
    static void AttachNodeSubMeshes(Model &dst,const GLTFModel &src){ for(int32_t ni=0; ni<(int32_t)src.nodes.size(); ++ni){ const auto &node=src.nodes[(size_t)ni]; auto &pn=dst.mesh_nodes[(size_t)ni]; if(node.mesh){ const auto &mesh=src.meshes[(size_t)*node.mesh]; pn.subMeshes.reserve(mesh.primitives.size()); for(auto primIndex: mesh.primitives) pn.subMeshes.push_back((int32_t)primIndex); } } }
    static void ComputeAllBounds(Model &dst){ ComputeAllMeshNodeBounds(dst); ComputeAllSceneBounds(dst); }
} // anonymous

Model ConvertFromGLTF(const GLTFModel &src){ Model dst; dst.gltf_source=src.source; CopyMaterials(dst, src); CopyScenes(dst, src); CopyMeshNodesAndTransforms(dst, src); auto uniqueMap=BuildUniqueGeometryMapping(src); CreateUniqueGeometryEntries(dst, src, uniqueMap); BuildSubMeshes(dst, src, uniqueMap); AttachNodeSubMeshes(dst, src); ComputeAllBounds(dst); return dst; }

} // namespace pure
